extra_css:
    - css/custom.css
markdown_extensions:
    - pymdownx.tasklist
plugins:
    - search
site_name: My Docs
site_description: Michael Phillips journal
use_directory_urls: false
strict: true
